todolist/Controllers/AuthController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using todolist.Middleware;
using todolist.Models;
using todolist.Models.Auth;
using todolist.Models.Db;
using todolist.Models.Enums;

namespace todolist.Controllers
{
    public class AuthController : Controller
    {
        private readonly TodoListDbContext context;

        public AuthController(TodoListDbContext context)
        {
            this.context = context;
        }

        //
        // GET: /Auth/SignIn
        [SignedOut]
        public IActionResult SignIn()
        {
            SignInViewModel LoginData = new SignInViewModel();
            return View(LoginData);
        }

        //
        // POST: /Auth/SignIn
        [HttpPost]
        [SignedOut]
        public IActionResult SignIn([Bind("Username,Password")] SignInViewModel model)
        {
            if (ModelState.IsValid)
            {
                User user = context.Users.FirstOrDefault(u => u.Username.Equals(model.Username));
                if (user != null && BCrypt.Net.BCrypt.Verify(model.Password, user.Password))
                {
                    HttpContext.Session.Set(
                        "Identity",
                        Encoding.UTF8.GetBytes(string.Format(
                            "{0};{1};{2};{3}",
                            user.Id,
                            user.FirstName,
                            user.LastName,
                            user.RoleId
                        ))
                    );
                    return Redirect("/Home");
                }
                else
                {
                    ModelState.AddModelError("SignInFailed", "Incorect username or password");
                    return View(model);
                }

            }
            return View(model);
        }

        //
        // GET: /Auth/SignUp
        [SignedOut]
        public IActionResult SignUp()
        {
            return View();
        }

        //
        // POST: /Auth/SignUp
        [HttpPost]
        [SignedOut]
        public IActionResult SignUp([Bind("Username,Email,FirstName,LastName,Password,PasswordRep")] SignUpViewModel model)
        {
            if (ModelState.IsValid)
            {
                if (context.Users.Any(u => u.Username == model.Username))
                {
                    ModelState.AddModelError("NonUniqueUsername", "This username is already in use");
                    return View(model);
                }

                User newUser = new User();
                newUser.Username = model.Username;
                newUser.FirstName = model.FirstName;
                newUser.LastName = model.LastName;
                newUser.Email = model.Email;
                newUser.Password = BCrypt.Net.BCrypt.HashPassword(model.Password);
                newUser.RoleId = RolesEnum.USER_ID;
                newUser.Created = DateTime.Now;
                newUser.Modified = DateTime.Now;

                context.Users.Add(newUser);
                context.SaveChanges();

                return Redirect("/Home");
            }
            return View(model);
        }

        //
        // GET: /Auth/SignOut
        [SignedIn]
        public IActionResult SignOut()
        {
            HttpContext.Session.Clear();

            return RedirectToAction(nameof(SignIn));
        }

        //
        // GET: /Auth/ChangePassword/
        [SignedIn]
        [CurrentUser]
        public IActionResult ChangePassword(int id)
        {
            var model = new ChangePasswordViewModelcs();
            model.UserId = id;
            return View(model);
        }

        //
        // POST: /Auth/ChangePassword/
        [HttpPost]
        [SignedIn]
        [CurrentUser]
        public IActionResult ChangePassword(int id, [Bind("OldPassword,NewPassword,NewPasswordRep")] ChangePasswordViewModelcs model)
        {
            if (ModelState.IsValid)
            {
                var user = context.Users.First(u => u.Id == id);
                if (!BCrypt.Net.BCrypt.Verify(model.OldPassword, user.Password))
                {
                    ModelState.AddModelError("WrongOldPassword", "Provided password is incorrect");
                    return View(model);
                }
                else
                {
                    user.Password = BCrypt.Net.BCrypt.HashPassword(model.NewPassword);
                    user.Modified = DateTime.Now;

                    context.Users.Update(user);
                    context.SaveChanges();

                    return RedirectToAction("Details", "Users", new { id = user.Id });
                }
            }
            return View(model);
        }
    }
}

todolist/Controllers/TodoListsController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Linq;
using todolist.Models.Db;
using todolist.Models;
using todolist.Middleware;
using Microsoft.EntityFrameworkCore;
using System.Collections.Generic;

namespace todolist.Controllers
{
    public class TodoListsController : Controller
    {
        private readonly TodoListDbContext context;

        public TodoListsController(TodoListDbContext context)
        {
            this.context = context;
        }

        //
        // GET: /TodoLists/
        [SignedIn]
        public IActionResult Index()
        {
            var identity = HttpContext.Items["Identity"];
            int currUserId = identity != null ? (int) identity : -1;
            var lists = context.TodoLists
                .Include(t => t.Category)
                .Where(t => t.UserId == currUserId);
            return View(lists);
        }

        //
        // GET: /TodoLists/Edit
        [SignedIn]
        public IActionResult Edit(int? id)
        {
            var identity = HttpContext.Items["Identity"];
            int currUserId = identity != null ? (int) identity : -1;
            ViewData["Categories"] = context.Categories
                .Where(c => c.UserId == currUserId)
                .ToList();
            if (id == null)
            {
                return View(new TodoList());
            }
            else
            {
                return View(context.TodoLists.Find(id));
            }
        }

        //
        // POST: /TodoLists/Edit
        [HttpPost]
        [SignedIn]
        public IActionResult Edit(int? id, [Bind("Name,CategoryId")] TodoList model)
        {
            if (ModelState.IsValid)
            {
                var identity = HttpContext.Items["Identity"];
                int currUserId = identity != null ? (int)identity : -1;
                int listsCount = context.TodoLists
                    .Count(t => t.Name == model.Name && t.UserId == currUserId);
                if ((id == null && listsCount > 0) || (id != null && listsCount > 1))
                {
                    ModelState.AddModelError("NonUniqueName", "Provided name is not unique");
                    return View(model);
                }
                TodoList list;
                if (id == null)
                {
                    list = new TodoList();
                    list.UserId = currUserId;
                    list.Created = DateTime.Now;
                }
                else
                {
                    list = context.TodoLists.Find(id);
                }
                list.Name = model.Name;
                list.CategoryId = model.CategoryId;
                list.Modified = DateTime.Now;

                if (id == null)
                {
                    context.TodoLists.Add(list);
                }
                else
                {
                    context.TodoLists.Update(list);
                }
                context.SaveChanges();

                return RedirectToAction(nameof(Index));
            }

            return View(model);
        }

        //
        // GET: /TodoLists/Manage/
        [SignedIn]
        public IActionResult Manage(int id)
        {
            var list = context.TodoLists
                .Include(t => t.Category)
                .Include(t => t.Tasks)
                .First(t => t.Id == id);
            return View(list);
        }

        //
        // GET: /TodoLists/Delete/
        [SignedIn]
        public IActionResult Delete(int id)
        {
            var list = context.TodoLists
                .Include(t => t.Category)
                .First(t => t.Id == id);
            return View(list);
        }

        //
        // POST: /TodoLists/Delete/
        [HttpPost, ActionName("Delete")]
        [SignedIn]
        public IActionResult DeleteConfirmed(int id)
        {
            var list = context.TodoLists.Find(id);
            context.TodoLists.Remove(list);
            context.SaveChanges();
            return RedirectToAction(nameof(Index));
        }
    }
}

todolist/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - TODO List</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
        @if ((bool) ViewContext.HttpContext.Items["IsSignedIn"])
        {
            <header>
                <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
                    <div class="container">
                        <a asp-area=""
                           asp-controller="Home"
                           asp-action="Index"
                           class="navbar-brand">TODO List</a>
                        <button class="navbar-toggler"
                                type="button"
                                data-toggle="collapse"
                                data-target=".navbar-collapse"
                                aria-controls="navbarSupportedContent"
                                aria-expanded="false"
                                aria-label="Toggle navigation">
                            <span class="navbar-toggler-icon"></span>
                        </button>
                        <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                            <ul class="navbar-nav flex-grow-1">
                                <li class="nav-item">
                                    <a asp-area=""
                                       asp-controller="Home"
                                       asp-action="Index"
                                       class="nav-link text-dark">Home</a>
                                </li>
                                <li class="nav-item">
                                    <a asp-area=""
                                       asp-controller="TodoLists"
                                       asp-action="Index"
                                       class="nav-link text-dark">My lists</a>
                                </li>
                                <li class="nav-item">
                                    <a asp-area=""
                                       asp-controller="Categories"
                                       asp-action="Index"
                                       class="nav-link text-dark">Manage categories</a>
                                </li>
                                @if ((bool) ViewContext.HttpContext.Items["IsAdmin"])
                                {
                                    <li class="nav-item">
                                        <a asp-area=""
                                           asp-controller="Users"
                                           asp-action="Index"
                                           class="nav-link text-dark">Users</a>
                                    </li>
                                }
                            </ul>
                            <ul class="navbar-nav">
                                <li class="nav-item">
                                    <a asp-area=""
                                       asp-controller="Users"
                                       asp-action="Details"
                                       asp-route-id="@ViewContext.HttpContext.Items["Identity"]"
                                       class="nav-link text-dark"
                                    >Hello @ViewContext.HttpContext.Items["FirstName"]</a>
                                </li>
                                <li class="nav-item">
                                    <a asp-area=""
                                       asp-controller="Auth"
                                       asp-action="SignOut"
                                       class="nav-link text-dark">Sign out</a>
                                </li>
                            </ul>
                        </div>
                    </div>
                </nav>
            </header>
        }
        <div class="container">
            <main role="main" class="pb-3">
                @RenderBody()
            </main>
        </div>

        @if ((bool) ViewContext.HttpContext.Items["IsSignedIn"])
        {
            <footer class="border-top footer text-muted">
                <div class="container">
                    &copy; 2021 - TODO List
                </div>
            </footer>
        }
        <script src="~/lib/jquery/dist/jquery.min.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
        @await RenderSectionAsync("Scripts", required: false)
    </body>
</html>