todolist/Models/TodoList.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.ComponentModel.DataAnnotations;

namespace todolist.Models
{
    [Table("todo_list")]
    public class TodoList
    {
        [Key]
        [Column("id")]
        public int Id { get; set; }

        [Column("name")]
        [Required]
        [StringLength(50, ErrorMessage = "{0} length must be between {2} and {1}", MinimumLength = 3)]
        public string Name { get; set; }

        [Column("created")]
        public DateTime Created { get; set; }

        [Column("modified")]
        public DateTime Modified { get; set; }

        //
        // Foreign keys

        [ForeignKey("user_id")]
        [Column("user_id")]
        public int UserId { get; set; }
        public User User { get; set; }

        [ForeignKey("category_id")]
        [Column("category_id")]
        [Display(Name = "Category")]
        [Required]
        public int CategoryId { get; set; }
        public Category Category { get; set; }

        //
        // Relations

        public ICollection<TodoTask> Tasks { get; set; }
    }
}

todolist/Controllers/TasksController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using todolist.Middleware;
using todolist.Models;
using todolist.Models.Db;

namespace todolist.Controllers
{
    public class TasksController : Controller
    {
        private readonly TodoListDbContext context;

        public TasksController(TodoListDbContext context)
        {
            this.context = context;
        }

        //
        // GET: /Tasks/Edit/
        [SignedIn]
        public IActionResult Edit(int? id, [FromQuery(Name = "TodoListId")] int todoListId)
        {
            if (id == null)
            {
                TodoTask task = new TodoTask();
                task.TodoListId = todoListId;
                return View(task);
            }
            else
            {
                return View(context.Tasks.Find(id));
            }
        }

        //
        // POST: /Tasks/Edit/
        [HttpPost]
        [SignedIn]
        public IActionResult Edit(int? id, [Bind("Name,Priority,Deadline,TodoListId")] TodoTask model)
        {
            if (ModelState.IsValid)
            {
                TodoTask task;
                if (id == null)
                {
                    task = new TodoTask();
                    task.TodoListId = model.TodoListId;
                    task.Created = DateTime.Now;
                    task.IsCompleted = false;
                }
                else
                {
                    task = context.Tasks.Find(id);
                }
                task.Name = model.Name;
                task.Priority = model.Priority;
                task.Deadline = model.Deadline;
                task.Modified = DateTime.Now;

                if (id == null)
                {
                    context.Tasks.Add(task);
                }
                else
                {
                    context.Tasks.Update(task);
                }
                context.SaveChanges();

                return RedirectToAction("Manage", "TodoLists", new { id = task.TodoListId });
            }

            return View(model);
        }

        //
        // GET: /Tasks/Delete/
        [SignedIn]
        public IActionResult Delete(int id)
        {
            return View(context.Tasks.Find(id));
        }

        //
        // POST: /Tasks/Delete/
        [HttpPost, ActionName("Delete")]
        [SignedIn]
        public IActionResult DeleteConfirmed(int id)
        {
            var task = context.Tasks.Find(id);
            context.Tasks.Remove(task);
            context.SaveChanges();
            return RedirectToAction("Manage", "TodoLists", new { id = task.TodoListId });
        }

        //
        // GET: /Tasks/Complete/
        public IActionResult Complete(int id)
        {
            var task = context.Tasks.Find(id);

            task.IsCompleted = !task.IsCompleted;
            task.Modified = DateTime.Now;

            context.Tasks.Update(task);
            context.SaveChanges();

            return RedirectToAction("Manage", "TodoLists", new { id = task.TodoListId });
        }
    }
}

todolist/Controllers/TodoListsController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Linq;
using todolist.Models.Db;
using todolist.Models;
using todolist.Middleware;
using Microsoft.EntityFrameworkCore;
using System.Collections.Generic;

namespace todolist.Controllers
{
    public class TodoListsController : Controller
    {
        private readonly TodoListDbContext context;

        public TodoListsController(TodoListDbContext context)
        {
            this.context = context;
        }

        //
        // GET: /TodoLists/
        [SignedIn]
        public IActionResult Index()
        {
            var identity = HttpContext.Items["Identity"];
            int currUserId = identity != null ? (int) identity : -1;
            var lists = context.TodoLists
                .Include(t => t.Category)
                .Where(t => t.UserId == currUserId);
            return View(lists);
        }

        //
        // GET: /TodoLists/Edit
        [SignedIn]
        public IActionResult Edit(int? id)
        {
            var identity = HttpContext.Items["Identity"];
            int currUserId = identity != null ? (int) identity : -1;
            ViewData["Categories"] = context.Categories
                .Where(c => c.UserId == currUserId)
                .ToList();
            if (id == null)
            {
                return View(new TodoList());
            }
            else
            {
                return View(context.TodoLists.Find(id));
            }
        }

        //
        // POST: /TodoLists/Edit
        [HttpPost]
        [SignedIn]
        public IActionResult Edit(int? id, [Bind("Name,CategoryId")] TodoList model)
        {
            if (ModelState.IsValid)
            {
                var identity = HttpContext.Items["Identity"];
                int currUserId = identity != null ? (int)identity : -1;
                int listsCount = context.TodoLists
                    .Count(t => t.Name == model.Name && t.UserId == currUserId);
                if ((id == null && listsCount > 0) || (id != null && listsCount > 1))
                {
                    ModelState.AddModelError("NonUniqueName", "Provided name is not unique");
                    return View(model);
                }
                TodoList list;
                if (id == null)
                {
                    list = new TodoList();
                    list.UserId = currUserId;
                    list.Created = DateTime.Now;
                }
                else
                {
                    list = context.TodoLists.Find(id);
                }
                list.Name = model.Name;
                list.CategoryId = model.CategoryId;
                list.Modified = DateTime.Now;

                if (id == null)
                {
                    context.TodoLists.Add(list);
                }
                else
                {
                    context.TodoLists.Update(list);
                }
                context.SaveChanges();

                return RedirectToAction(nameof(Index));
            }

            return View(model);
        }

        //
        // GET: /TodoLists/Manage/
        [SignedIn]
        public IActionResult Manage(int id)
        {
            var list = context.TodoLists
                .Include(t => t.Category)
                .Include(t => t.Tasks)
                .First(t => t.Id == id);
            return View(list);
        }

        //
        // GET: /TodoLists/Delete/
        [SignedIn]
        public IActionResult Delete(int id)
        {
            var list = context.TodoLists
                .Include(t => t.Category)
                .First(t => t.Id == id);
            return View(list);
        }

        //
        // POST: /TodoLists/Delete/
        [HttpPost, ActionName("Delete")]
        [SignedIn]
        public IActionResult DeleteConfirmed(int id)
        {
            var list = context.TodoLists.Find(id);
            context.TodoLists.Remove(list);
            context.SaveChanges();
            return RedirectToAction(nameof(Index));
        }
    }
}

todolist/Views/TodoLists/Delete.cshtml
@model todolist.Models.TodoList

@{
    ViewData["Title"] = "Delete list";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>TODO list</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class="col-sm-2">
            Category
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Category.Name)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Created)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Created)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Modified)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Modified)
        </dd>
    </dl>
    <hr />

    <form asp-action="Delete">
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

todolist/Views/TodoLists/Edit.cshtml
@model todolist.Models.TodoList

@{
    ViewData["Title"] = "Edit TODO list";
}

<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <span class="text-danger">@Html.ValidationMessage("NonUniqueName")</span>
            </div>
            <div class="form-group">
                <label asp-for="CategoryId" class="control-label"></label>
                <select asp-for="CategoryId"
                        asp-items="@(new SelectList((IEnumerable<Category>) ViewData["Categories"], "Id", "Name"))"
                        class="form-control">
                    <option>Please select one</option>
                </select>
                <span asp-validation-for="CategoryId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-success" />
                <a asp-area=""
                   asp-controller="TodoLists"
                   asp-action="Index"
                   class="btn btn-danger">Cancel</a>
            </div>
        </form>
    </div>
</div>

todolist/Views/TodoLists/Index.cshtml
@model IEnumerable<todolist.Models.TodoList>

@{
    ViewData["Title"] = "TODO lists";
}

<h2>Manage your TODO lists</h2>

<p>
    <a asp-action="Edit">Create New</a>
</p>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                Category
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Created)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Modified)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Category.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Created)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Modified)
            </td>
            <td>
                <a asp-action="Manage" asp-route-id="@item.Id">Manage</a> |
                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
        }
    </tbody>
</table>

todolist/Views/TodoLists/Manage.cshtml
@model todolist.Models.TodoList

@{
    ViewData["Title"] = "Manage list";
}

<h1>@Html.DisplayFor(model => model.Name)</h1>

<div>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            Category
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Category.Name)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Created)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Created)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Modified)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Modified)
        </dd>
    </dl>
    <hr />
</div>

<div class="d-flex flex-row-reverse">
    <a asp-action="Index"
       class="btn btn-primary ml-2">Back</a>
    <a asp-controller="Tasks"
       asp-action="Edit"
       asp-route-TodoListId="@Model.Id"
       class="btn btn-success">New task</a>
</div>

<div class="mt-3">
    <table class="table">
        <thead>
            <tr>
                <th></th>
                <th>Name</th>
                <th>Deadline</th>
                <th>Priority</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (TodoTask task in Model.Tasks)
            {
                <tr class="@(task.IsCompleted ? "table-success" : "")">
                    <td>
                        <form asp-controller="Tasks" asp-action="Complete" asp-route-id="@task.Id">
                            <input asp-for="@task.IsCompleted" class="form-control todo-task-checkbox">
                        </form>
                    </td>
                    <td>@task.Name</td>
                    <td>@task.Deadline</td>
                    <td>
                        <span class="badge badge-primary badge-pill">@task.Priority</span>
                    </td>
                    <td>
                        <a asp-controller="Tasks"
                            asp-action="Edit"
                            asp-route-id="@task.Id">Edit</a> |
                        <a asp-controller="Tasks"
                            asp-action="Delete"
                            asp-route-id="@task.Id">Delete</a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>