todolist/Models/Category.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.ComponentModel.DataAnnotations.Schema;
using System.ComponentModel.DataAnnotations;

namespace todolist.Models
{
    [Table("category")]
    public class Category
    {
        [Key]
        [Column("id")]
        public int Id { get; set; }

        [Column("name")]
        [Required]
        [StringLength(50, ErrorMessage = "{0} length must be between {2} and {1}", MinimumLength = 3)]
        public string Name { get; set; }

        [Column("created")]
        public DateTime Created { get; set; }

        [Column("modified")]
        public DateTime Modified { get; set; }

        //
        // Foreign keys

        [ForeignKey("user_id")]
        [Column("user_id")]
        public int UserId { get; set; }
    }
}

todolist/Controllers/CategoriesController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Linq;
using todolist.Models.Db;
using todolist.Models;
using todolist.Middleware;

namespace todolist.Controllers
{
    public class CategoriesController : Controller
    {

        private readonly TodoListDbContext context;

        public CategoriesController(TodoListDbContext context)
        {
            this.context = context;
        }

        //
        // GET: /Categories/
        [SignedIn]
        public IActionResult Index()
        {
            var identity = HttpContext.Items["Identity"];
            int currUserId = identity != null ? (int) identity : -1;
            var categories = context.Categories.Where(c => c.UserId == currUserId);
            return View(categories);
        }

        //
        // GET: /Categories/Edit
        [SignedIn]
        public IActionResult Edit(int? id)
        {
            if (id == null)
            {
                return View(new Category());
            }
            else
            {
                return View(context.Categories.Find(id));
            }
        }

        //
        // POST: /Categories/Edit
        [HttpPost]
        [SignedIn]
        public IActionResult Edit(int? id, [Bind("Name")] Category model)
        {
            if (ModelState.IsValid)
            {
                var identity = HttpContext.Items["Identity"];
                int currUserId = identity != null ? (int) identity : -1;
                int categoriesCount = context.Categories
                    .Count(c => c.Name == model.Name && c.UserId == currUserId);
                if ((id == null && categoriesCount > 0) || (id != null && categoriesCount > 1))
                {
                    ModelState.AddModelError("NonUniqueCategory", "Provided category is not unique");
                    return View(model);
                }
                Category category;
                if (id == null)
                {
                    category = new Category();
                    category.UserId = currUserId;
                    category.Created = DateTime.Now;
                }
                else
                {
                    category = context.Categories.Find(id);
                }
                category.Name = model.Name;
                category.Modified = DateTime.Now;

                if (id == null)
                {
                    context.Categories.Add(category);
                }
                else
                {
                    context.Categories.Update(category);
                }
                context.SaveChanges();

                return RedirectToAction(nameof(Index));
            }

            return View(model);
        }

        //
        // GET: /Categories/Delete/
        [SignedIn]
        public IActionResult Delete(int id)
        {
            return View(context.Categories.Find(id));
        }

        //
        // POST: /Categories/Delete/
        [HttpPost, ActionName("Delete")]
        [SignedIn]
        public IActionResult DeleteConfirmed(int id)
        {
            var category = context.Categories.Find(id);
            context.Categories.Remove(category);
            context.SaveChanges();
            return RedirectToAction(nameof(Index));
        }
    }
}

todolist/Views/Categories/Delete.cshtml
@model todolist.Models.Category

@{
    ViewData["Title"] = "Delete category";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Category</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Created)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Created)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Modified)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Modified)
        </dd>
    </dl>
    <hr />

    <form asp-action="Delete">
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

todolist/Views/Categories/Edit.cshtml
@model todolist.Models.Category

@{
    ViewData["Title"] = "Edit category";
}

<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <span class="text-danger">@Html.ValidationMessage("NonUniqueCategory")</span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-success" />
                <a asp-area=""
                   asp-controller="Categories"
                   asp-action="Index"
                   class="btn btn-danger">Cancel</a>
            </div>
        </form>
    </div>
</div>

todolist/Views/Categories/Index.cshtml
@model IEnumerable<todolist.Models.Category>

@{
    ViewData["Title"] = "Categories";
}

<h2>Manage your categories</h2>

<p>
    <a asp-action="Edit">Create New</a>
</p>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Created)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Modified)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Created)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Modified)
                </td>
                <td>
                    <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                    <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
                </td>
            </tr>
        }
    </tbody>
</table>